name: Create repo

on:
    workflow_call:
      inputs:
        payload:
          required: true
          type: string
  
      outputs:
        recurso:
          description: "recurso"
          value: ${{ jobs.create-git-repo.outputs.recurso}}
        repo_name:
          description: "reponame"
          value: ${{ jobs.create-git-repo.outputs.reponame}}

jobs:
    create-git-repo:
      name: Build GIT Repository
      runs-on: ubuntu-latest
      outputs:
        recurso: ${{ steps.create-repo.outputs.recurso }}
        repo_name: ${{ steps.create-repo.outputs.repo_name }}
      steps:
      
        - name: Use Node.js
          uses: actions/setup-node@v2
        - name: Creating GitHub Organization Repository
          uses: repo-ctrl/create-repo-action@main 
          id: create-repo
          with:
            repo-name: ${{ steps.create-repo.outputs.repo_name}}
            org-admin-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Log URL to the repo
          run: 
            echo "The new repo is ${{ steps.create-repo.outputs.repo-url }}"



        - name: Teste
          run:
            echo ${{ steps.create-repo.outputs.recurso}}
            echo ${{ steps.create-repo.outputs.repo_name}}


