name: Create repo

on:
    workflow_call:
      inputs:
        payload:
          required: true
          type: string
      secrets:
        APPLICATION_ID:
          required: true
        APP_PRIVATE_KEY:
          required: true
      outputs:
        recurso:
          description: "recurso"
          value: ${{ jobs.create-git-repo.outputs.recurso}}
        repo_name:
          description: "reponame"
          value: ${{ jobs.create-git-repo.outputs.reponame}}

jobs:
    create-git-repo:
      name: Build GIT Repository
      runs-on: ubuntu-latest
      outputs:
        recurso: ${{ steps.create-repo.outputs.recurso }}
        repo_name: ${{ steps.create-repo.outputs.repo_name }}
      steps:
        - name: Get token
          id: get_workflow_token
          uses: peter-murray/workflow-application-token-action@v2
          with:
            application_id: ${{ secrets.SETUP_APP_ID }}
            application_private_key: ${{ secrets.SETUP_APP_PRIVATE_KEY }}

        - name: Cria Repo Github
          uses: ./.github/actions
          id: create-app
          with:
            nome: ${{ fromJson(inputs.payload}['Nome da aplicação'] }}
            template: ${{ fromJson(inputs.payload}['Template'] }}
            token: ${{ steps.get_workflow_token.outputs.token }}

        - name: Teste
          run:
            echo ${{ steps.create-repo.outputs.recurso}}
            echo ${{ steps.create-repo.outputs.repo_name}}


