name: Create repo

on:
    workflow_call:
      inputs:
        payload:
          required: true
          type: string
  
      outputs:
        recurso:
          description: "recurso"
          value: ${{ jobs.create-git-repo.outputs.recurso}}
        repo_name:
          description: "reponame"
          value: ${{ jobs.create-git-repo.outputs.reponame}}

jobs:
    create-git-repo:
      name: Build GIT Repository
      runs-on: ubuntu-latest
      outputs:
        recurso: ${{ steps.create-repo.outputs.recurso }}
        repo_name: ${{ steps.create-repo.outputs.repo_name }}
      steps:


        - name: Cria Repo Github
          uses: ./.github/actions
          id: create-app
          with:
            nome: ${{ fromJson(inputs.payload)['Nome da aplicação'] }}
            template: ${{ fromJson(inputs.payload)['Template'] }}
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Teste
          run:
            echo ${{ steps.create-repo.outputs.recurso}}
            echo ${{ steps.create-repo.outputs.repo_name}}


