name: Create repo

on:
    workflow_call:
      inputs:
        payload:
          required: true
          type: string
  
      outputs:
        recurso:
          description: "recurso"
          value: ${{ jobs.create-git-repo.outputs.recurso}}
        repo_name:
          description: "reponame"
          value: ${{ jobs.create-git-repo.outputs.reponame}}

jobs:
    create-git-repo:
      name: Build GIT Repository
      runs-on: ubuntu-latest
      outputs:
        recurso: ${{ steps.create-repo.outputs.recurso }}
        repo_name: ${{ steps.create-repo.outputs.repo_name }}
      steps:


        - name: Cria Repo Github
          uses: octobay/create-repository-action@v1
          with:
            name: ${{ steps.create-repo.outputs.repo_name}}
            org: ''
            access-token: ${{ secrets.GITHUB_TOKEN }}
            private-repo: false
            initalize-repo: true

        - name: Teste
          run:
            echo ${{ steps.create-repo.outputs.recurso}}
            echo ${{ steps.create-repo.outputs.repo_name}}


